/*Problem Statement:
You are a database administrator. You want to use the data to answer afewquestions about your customers,
especially about the sales and profit comingfrom different states, money spent in marketing and various other
factorssuchasCOGS (Cost of Goods Sold), budget profit etc. You plan on using theseinsightsto help find out which
items are being sold the most. You have beenprovidedwith the sample of the overall customer data due to privacy issues.
But youhopethat these samples are enough for you to write fully functioning SQLqueriestohelp answer the questions.


Dataset:
The 3 key datasets for this case study:
a. FactTable: The Fact Table has 14 columns mentioned belowand4200rows.
Date, ProductID, Profit, Sales, Margin, COGS, Total Expenses, Marketing,
Inventory, Budget Profit, Budget COGS, Budget Margin, Budget
Sales, and Area Code
Note: COGS stands for Cost of Goods Sold

b. ProductTable: The ProductTable has four columns named Product Type, Product, ProductID, and Type.
It has 13 rows which can be brokendowninto further details to retrieve the information mentioned in theFactTable.

c. LocationTable: Finally, the LocationTable has 156 rows andfollowsasimilar approach to ProductTable.
It has four columns named AreaCode, State, Market, and Market Size.

Tasks to be performed:
1. Display the number of states present in the LocationTable.
2. How many products are of regular type?
3. How much spending has been done on marketing of product ID 1?
4. What is the minimum sales of a product?
5. Display the max Cost of Good Sold (COGS).
6. Display the details of the product where product type is coffee.
7. Display the details where total expenses are greater than 40.
8. What is the average sales in area code 719?
9. Find out the total profit generated by Colorado state.
10. Display the average inventory for each product ID.
11. Display state in a sequential order in a Location Table.
12. Display the average budget of the Product where the average budget
margin should be greater than 100.
13. What is the total sales done on date 2010-01-01?
14. Display the average total expense of each product ID on an individual date.
15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.
16. Display the rank without any gap to show the sales wise rank.
17. Find the state wise profit and sales.
18. Find the state wise profit and sales along with the productname.
19. If there is an increase in sales of 5%, calculate the increasedsales.
20. Find the maximum profit along with the product ID and producttype.
21. Create a stored procedure to fetch the result according to the product typefrom Product Table
22. Write a query by creating a condition in which if the total expenses is lessthan60 then it is a profit or else loss.
23. Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order.
24. Apply union and intersection operator on the tables which consist of
attribute area code. 
25. Create a user-defined function for the product table to fetch a particular
product type based upon the user’s preference.
26. Change the product type from coffee to tea where product IDis 1 andundoit.
27. Display the date, product ID and sales where total expenses are
between 100 to 200. 
28. Delete the records in the Product Table for regular type. 
29. Display the ASCII value of the fifth character from the columnProduct.*/


SELECT * FROM fact
SELECT * FROM Product
SELECT * FROM Location

--1. Display the number of states present in the LocationTable.

SELECT DISTINCT State from Location.

--2. How many products are of regular type?

select count(Product_Type) over(partition by Type,Product_Type) number_of_product 
,Product_Type,Type from Product where Type = 'Regular'

SELECT count(distinct Product_Type)
FROM (
    SELECT 
        COUNT(Product_Type) OVER (PARTITION BY Type, Product_Type) AS number_of_product,
        Product_Type,
        Type
    FROM Product
    WHERE Type = 'Regular'
) AS SFS;

--3. How much spending has been done on marketing of product ID 1?

SELECT * FROM fact
SELECT * FROM Product
SELECT * FROM Location

select sum(Marketing) [Spending on product id 1] from fact where ProductId = 1

--4. What is the minimum sales of a product?
select Top 1 Total_sum_of_sales,ProductId from (
Select sum(Sales) Total_sum_of_sales,ProductId 
from Fact group by ProductId  ) as ade order by Total_sum_of_sales 

--5. Display the max Cost of Good Sold (COGS).
select top 1  [Total sum of cost of good sold] ,ProductID from (
Select sum(COGS) [Total sum of cost of good sold] ,ProductId from fact group by ProductId) as df 
order by [Total sum of cost of good sold] desc

--6. Display the details of the product where product type is coffee.

Select * from fact f join 
Location l on f.Area_Code = l.Area_Code join Product p on f.ProductId  = p.ProductId where p.Product_Type = 'Coffee'

--7. Display the details where total expenses are greater than 40.

select * from fact where Total_Expenses > 40

--8. What is the average sales in area code 719?

Select *,avg(Sales)  over() avg_sales from fact where Area_Code = 719

--9. Find out the total profit generated by Colorado state.

Select sum(Profit) Total_profit ,l.State
from fact f join 
Location l on f.Area_Code = l.Area_Code where l.State = 'Colorado' group by l.State;

--10. Display the average inventory for each product ID.

select *,avg(Inventory) over(partition by ProductId) avg_inventory from fact order by ProductId 

--11. Display state in a sequential order in a Location Table.

SELECT * FROM fact
SELECT * FROM Product
SELECT * FROM Location

SELECT * FROM LOCATION ORDER BY STATE

--12. Display the average budget of the Product where the average budget
--margin should be greater than 100.

Select avg(Budget_Margin) avg_budget_margin , productid from fact GROUP BY Productid having avg(Budget_Margin)>100


--13. What is the total sales done on date 2010-01-01?

SELECT   DATE,
       SUM(sales) TOTAL_SALES
	   FROM FACT  WHERE DATE = '2010-01-01' GROUP BY DATE;

--14. Display the average total expense of each product ID on an individual date.

SELECT * ,AVG(Total_Expenses) over(PARTITION by productid, date order by date)  avg_total_expenses from fact;  --(with the details)


select avg(Total_Expenses) avg_total_expenses ,ProductId ,date from fact group by date,ProductId order by date; --(without the details)

--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.

Select f.productID ,p.product_type,p.Product,f.Sales,f.Profit,l.State,f.Area_Code from fact f join 
Location l on f.Area_Code = l.Area_Code join Product p on f.ProductId  = p.ProductId 

--16. Display the rank without any gap to show the sales wise rank.

Select Productid,Tota_Saels, DENSE_RANK() over(order by Tota_Saels desc) Ranking_Sales_wise from (

Select Productid, sum(Sales)  Tota_Saels from fact group by ProductId ) as dfd 

--17. Find the state wise profit and sales.

Select sum(Sales) Tota_Sales,sum(Profit) Tota_Profit ,State 
from fact f join 
Location l on f.Area_Code = l.Area_Code group by State order by State 

--18. Find the state wise profit and sales along with the productname.

Select sum(Sales) over(partition by State ) Tota_Sales,sum(Profit) over(partition by State) Tota_Profit ,State ,PRODUCT
from fact f join 
Location l on f.Area_Code = l.Area_Code join Product p on 
f.ProductId = p.ProductId
 
 --19. If there is an increase in sales of 5%, calculate the increasedsales.

 Select (Sales *1.05) [increased sales] from fact 

 --20. Find the maximum profit along with the product ID and producttype.

Select max(Profit) over() max_profit ,f.ProductId ,p.Product_Type from fact f join
Product p on f.ProductId = p.ProductId 

--21. Create a stored procedure to fetch the result according to the product type from Product Table

create procedure product_type @product_type varchar(60)
as 
begin
select * 
from Product where Product_Type = @product_type;
end;

exec product_type @product_type = 'Coffee';

--22. Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss.

Select  case 
when Total_Expenses < 60 then 'Profit'
else 'loss'
end [checking the loss and profit on the basis of total expenses],*
from  fact

--23. Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order.

select * from fact

--24. Apply union and intersection operator on the tables which consist of
--attribute area code.


SELECT Area_Code
FROM Fact

UNION        
SELECT Area_Code
FROM Location;

--25. Create a user-defined function for the product table to fetch a particular
--product type based upon the user’s preference.

SELECT * FROM fact
SELECT * FROM Product
SELECT * FROM Location

Create function product_table(@product varchar(50))
returns table 
as 
return 
(
Select * from Product where Product_Type = @product);

select * from product_table('Coffee')

--26. Change the product type from coffee to tea where product ID is 1 and undo it.


update Product set Product_Type = REPLACE('Coffee','Coffee','tea') where ProductId =1
select * from Product

update Product set Product_Type = REPLACE('Coffee','Coffee','Coffee') where ProductId =1

--27. Display the date, product ID and sales where total expenses are
--between 100 to 200.

Select date , productid,sales from fact where Total_Expenses between 100 and  200;

--28. Delete the records in the Product Table for regular type. 

Select * from Product 

delete  from Product  where type = 'Regular'

--29. Display the ASCII value of the fifth character from the column Product.*/


SELECT 
    Product,
    ASCII(SUBSTRING(Product, 5, 1)) AS FifthChar_ASCII
FROM Product;
